version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - custom-network

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
    name: custom_network